# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 464edecc918c4012ec28a0a6efe3ce8f464edecc918c4012ec28a0a6efe3ce8f464edecc918c4012ec28a0a6efe3ce8f464edecc918c4012ec28a0a6efe3ce8f

devise:
  jwt_secret_key: d7bc50f70bee26c86a9b9a6addebd02215c4f21438b7ffd3a49638102867be75d8f3e4ddf0dc05958aff54a6a1313c2130c80f299fe319de7dd19d58ac05bfda

# Environment specific secrets
development:
  # Any keys here will be accessible in Rails.application.credentials.development
  
production:
  # Any keys here will be accessible in Rails.application.credentials.production
